#pragma once
// STD Libraries
#include <iostream>
#include <sstream>
#include <vector>
#include <string>
#include <iomanip>
#include <cctype>
#include <algorithm>
#include <memory>    
#include <stdexcept>
#include <fstream>
#include <sstream>
#include <bitset>
#include <functional> 
#include <random>
#include "core/IEncryptor.h"
#include <fstream>
#include <iostream>
#include <vector>
#include <string>
#include <bitset>
#include <array>